#!/bin/bash 

DOCKER_VERSION=1.6.2

cd /tmp/ 
wget https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz 
tar zxf docker-${DOCKER_VERSION}.tgz 
mkdir -p /usr/local/bin/ 
mv $(find -name 'docker') /usr/local/bin/ 
chmod +x /usr/local/bin/docker 
rm -rf /tmp/* 
